name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

    deploy:

        name: Setup Gcloud Account
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.wsl-poc }}
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.wsl-poc }}
          
        
        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: docker build -t nginx .

        - name: Push Docker image
          run: docker push nginx

        - name: Deploy Docker image
          run: gcloud run deploy ${{ secrets.wsl-poc }} --image nginx --region us-central1 --platform managed
