name: Jmeter
on:
  push:
    branches:
      - master
    
jobs:
  Jmeter:
    name: Test
    runs-on: ubuntu-latest
    steps:
     - name: Checkout Repo
       uses: actions/checkout@v2
       
     - name: JMeter-Test
       uses: ./
       with:
         test-plan-path: ./testplan/result.jmx
         args: ""
     - name: Upload Results
       uses: actions/upload-artifact@v2
       with:
         name: jmeter-results
         path: result.jtl
