name: Jmeter
on:
  push:
    branches:
      - master
    
jobs:
  Jmeter:
    name: Test
    runs-on: ubuntu-latest
    steps:
     - name: JMeter Test
       uses: QAInsights/PerfAction@v3.1
       with:
         test-plan-path: C:\Software\apache-jmeter-5.5\apache-jmeter-5.5\bin\Load_test\resu;t.jmx
         args: ""
    - name: Upload Results
      uses: actions/upload-artifact@v2
      with:
       name: jmeter-results
       path: result.jtl
